tasks/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.task_list, name='task_list'),
    path('add/', views.task_add, name='task_add'),
    path('edit/<int:task_id>/', views.task_edit, name='task_edit'),
    path('tasks/remove/<int:task_id>', views.task_remove, name='task_remove'),
    path('tasks/toggle-completion/<int:task_id>', views.task_toggle_completion, name='task_toggle_completion')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo_list/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/models.py
from django.db import models

class Task(models.Model):
    TASK_TYPES = (
        ('regular', 'Zwykłe zadanie'),
        ('phone', 'Wykonać telefon'),
        ('email', 'Wysłać email'),
    )

    title = models.CharField(max_length=50)
    description = models.CharField(max_length=250)
    due_date = models.DateField()
    completed = models.BooleanField(default=False)
    task_type = models.CharField(max_length=10, choices=TASK_TYPES)
    phone = models.CharField(max_length=12, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)

    def __str__(self):
        return self.title

tasks/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Task


def task_list(request):
    tasks = Task.objects.all()
    return render(request, 'tasks/task_list.html', {'tasks': tasks})


def task_add(request):
    if request.method == 'POST':
        # Pobierz dane z formularza
        title = request.POST.get('title')
        description = request.POST.get('description')
        due_date = request.POST.get('due_date')
        completed = False
        task_type = request.POST.get('task_type')
        phone = request.POST.get('phone')
        email = request.POST.get('email')

        # Utwórz nowe zadanie
        task = Task.objects.create(
            title=title,
            description=description,
            due_date=due_date,
            completed=completed,
            task_type=task_type,
            phone=phone,
            email=email
        )

        return redirect('task_list')

    return render(request, 'tasks/task_add.html', {'task_type': None})


def task_edit(request, task_id):
    task = get_object_or_404(Task, id=task_id)

    if request.method == 'POST':
        # Pobierz dane z formularza
        task.title = request.POST.get('title')
        task.description = request.POST.get('description')
        task.due_date = request.POST.get('due_date')
        task.completed = False
        task.task_type = request.POST.get('task_type')
        task.phone = request.POST.get('phone')
        task.email = request.POST.get('email')

        task.save()
        return redirect('task_list')

    return render(request, 'tasks/task_edit.html', {'task': task})

def task_remove(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.delete()
    return redirect('task_list')

def task_toggle_completion(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.completed = not task.completed
    task.save()
    return redirect('task_list')

templates/tasks/task_add.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<h1>Dodaj nowe zadanie</h1>

<form method="post" action="{% url 'task_add' %}">
    {% csrf_token %}
    <label for="title">Tytuł:</label>
    <input type="text" name="title" required><br>
    <label for="description">Opis:</label>
    <input type="text" name="description" required><br>
    <label for="due_date">Termin realizacji:</label>
    <input type="date" name="due_date" required><br>
    <label for="task_type">Typ zadania:</label>
    <select name="task_type" id="task_type_select">
        <option value="regular">Zwykłe zadanie</option>
        <option value="phone">Wykonać telefon</option>
        <option value="email">Wysłać email</option>
    </select><br>
    <label for="phone">Telefon:</label>
    <input type="text" name="phone" id="phone_input" disabled><br>
    <label for="email">Email:</label>
    <input type="email" name="email" id="email_input" disabled><br>
    <button type="submit" class="button">Dodaj zadanie</button>
</form>

<script>
    // Get references to the select field and input fields
    const taskTypeSelect = document.getElementById('task_type_select');
    const phoneInput = document.getElementById('phone_input');
    const emailInput = document.getElementById('email_input');

    // Add event listener to the select field
    taskTypeSelect.addEventListener('change', function() {
        // Get the selected value
        const selectedValue = taskTypeSelect.value;

        // Enable/disable the corresponding input fields based on the selected value
        phoneInput.disabled = (selectedValue !== 'phone');
        emailInput.disabled = (selectedValue !== 'email');
    });
</script>

templates/tasks/task_edit.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<h1>Edytuj zadanie</h1>

<form method="post">
    {% csrf_token %}
    <label for="title">Tytuł:</label>
    <input type="text" name="title" value="{{ task.title }}" required><br>
    <label for="description">Opis:</label>
    <input type="text" name="description" value="{{ task.description }}" required><br>
    <label for="due_date">Termin realizacji:</label>
    <input type="date" name="due_date" value="{{ task.due_date }}" required><br>
    <label for="task_type">Typ zadania:</label>
    <select name="task_type" id="task_type_select">
      <option value="regular" {% if task.task_type == 'regular' %}selected{% endif %}>Zwykłe zadanie</option>
      <option value="phone" {% if task.task_type == 'phone' %}selected{% endif %}>Wykonać telefon</option>
      <option value="email" {% if task.task_type == 'email' %}selected{% endif %}>Wysłać email</option>
    </select><br>

    <label for="phone">Telefon:</label>
    <input type="text" name="phone" id="phone_input" value="{{ task.phone }}" {% if task.task_type != 'phone' %}disabled{% endif %}><br>
    <label for="email">Email:</label>
    <input type="email" name="email" id="email_input" value="{{ task.email }}" {% if task.task_type != 'email' %}disabled{% endif %}><br>
    <button type="submit" class="button">Zapisz zmiany</button>
</form>

<script>
    // Get references to the select field and input fields
    const taskTypeSelect = document.getElementById('task_type_select');
    const phoneInput = document.getElementById('phone_input');
    const emailInput = document.getElementById('email_input');

    // Add event listener to the select field
    taskTypeSelect.addEventListener('change', function() {
        // Get the selected value
        const selectedValue = taskTypeSelect.value;

        // Enable/disable the corresponding input fields based on the selected value
        phoneInput.disabled = (selectedValue !== 'phone');
        emailInput.disabled = (selectedValue !== 'email');
    });
</script>

templates/tasks/task_list.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<h1>Lista zadań</h1>

<ul>
    {% for task in tasks %}
        <li>
            <h3>{{ task.title }}</h3>
            <p>Opis: {{ task.description }}</p>
            <p>Termin realizacji: {{ task.due_date }}</p>
            <p>Status wykonania: {% if task.completed %}<button class="small-button" style="background-color: green">Wykonane</button>{% else %}<button class="small-button" style="background-color: red">Niewykonane</button>{% endif %} <a href="{% url 'task_toggle_completion' task.id %}" class="small-button">Zmień</a></p>

            <p>Typ zadania: {{ task.get_task_type_display }}</p>
            {% if task.task_type == 'phone' %}
                <p>Numer telefonu: {{ task.phone }}</p>
            {% elif task.task_type == 'email' %}
                <p>Adres email: {{ task.email }}</p>
            {% endif %}
            <a href="{% url 'task_edit' task.id %}" class="small-button">Zmień</a>
            <a href="{% url 'task_remove' task.id %}" class="small-button" style="background-color: red">Usuń</a>
        </li>
    {% endfor %}
</ul>

<a href="{% url 'task_add' %}" class="button">Dodaj nowe zadanie</a>